[package]
name = "auto_redshift"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
#todo = { "git" = "https://github.com/Valera6/todo.git" }
